kind: pipeline
name: dev
steps:
- name: test
  image: node:8
  commands:
    - npm install
    - npm test

- name: codecov
  image: node:8
  environment:
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN
  commands:
    - npm run test:codecov
  when:
    event:
    - push
    - rollback

trigger:
  event:
  - push
  - pull_request
  - promote
  - rollback

---
kind: pipeline
name: prod
steps:
- name: test
  image: node:8
  commands:
    - npm install
    - npm test

- name: docker
  image: plugins/docker
  settings:
    repo: piterjs/rocket-bot
    dockerfile: Dockerfile
    tags:
    - "${DRONE_TAG}"
    - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: deploy
  image: vallard/drone-kube
  environment:
    KUBE_SERVER:
      from_secret: KUBE_SERVER
    KUBE_TOKEN:
      from_secret: KUBE_TOKEN
    KUBE_CA:
      from_secret: KUBE_CA
  settings:
    template: deployment.yml
    namespace: chat

trigger:
  event:
  - tag

---
kind: pipeline
name: after

steps:
- name: notify
  image: mike1pol/drone-rocket
  settings:
    url:
      from_secret: rocket_url
    user_id:
      from_secret: rocket_id
    token:
      from_secret: rocket_token
    channel:
      from_secret: rocket_channel
    message: >
      {{#success build.status}}✅{{else}}❌{{/success}} Build {{build.status}}: *{{repo.namespace}}/{{repo.name}}*

      build: {{build.number}}

      commit: {{build.branch}}:{{build.commit}}

      By: {{build.author}}

      {{build.message}}

      {{build.link}}

depends_on:
- dev
- prod

trigger:
  status:
  - success
  - failure
